### ISSUE TITLE
Migration wagtailsvg.0001_initial dependencies reference nonexistent parent node ('wagtailcore', '0059_apply_collection_ordering')

### ISSUE THREAD

**Issue by mentecuantica** [Aleksi44/wagtailsvg#1]
`Migration wagtailsvg.0001_initial dependencies reference nonexistent parent node ('wagtailcore', '0059_apply_collection_ordering')`

Why i have such an issue?
my requirements.txt is:
```
Django==3.1.4
wagtail==2.10
gunicorn==20.0.4
psycopg2-binary==2.8.1
wagtailfontawesome==1.2.1
wagtailtrans==2.2
django-rosetta==0.9.2
social-auth-app-django==3.1.0
git+git://github.com/byashimov/typus.git#egg=typus
google-api-python-client==1.8.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
djangorestframework-recursive==0.1.2
sentry-sdk==0.7.10
wagtail-headless-preview==0.1.4
wagtailsvg==0.0.7
```

**Comment by Aleksi44** [comment]
`wagtailsvg` use Wagtail collection model.

Your version of Wagtail doesn't have the latest migration file of collection model (the last file [here](https://github.com/wagtail/wagtail/tree/master/wagtail/core/migrations))

You have 2 solutions :

- Solution 1 : update version of wagtail : pip install wagtail==2.11.3
- Solution 2 : fork `wagtailsvg`, delete and make migrations of `wagtailsvg` app with your wagtail version (2.10)

**Comment by mentecuantica** [comment]
thanks for quick reply!
