### ISSUE TITLE
Update wagtail-generic-chooser

### ISSUE THREAD

**Issue by vbabiy** [Aleksi44/wagtailsvg#24]
This package still requires a 0.4 the package has been updated to 0.5.1

**Comment by Aleksi44** [comment]
Hi @vbabiy 

Can you submit a pull request for that ?

**Comment by Aleksi44** [comment]
Thanks @vbabiy 

Just released : `wagtailsvg==0.0.36`

**Comment by vbabiy** [comment]
Looks like we didn't update the setup.py, will push a PR to fix this.
